server:
  port: 8083

redis:
  host: 127.0.0.1
  port: 6379
  auth: 123
  maxTotal: 20
  maxIdle: 5
  maxWaitMillis: 10000
  testOnBorrow: true
  testOnReturn: true
  dbIndex: 0



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=Hongkong&allowMultiQueries=true&characterEncoding=utf8&useUnicode=true&&characterSetResults=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zpark.ssm.booksystem.entity
  configuration:
    map-underscore-to-camel-case: true






